// File generated by FlutterFire CLI for project openaamps.
// Project ID: openaamps
// Android App: com.openaamps.open_aamps
// App ID: 1:777154173201:android:fc3b6f2f65b9468f0e94b0

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android; // Safe fallback for other platforms/simulators
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEky_XxWxdJ26FHZAUzScaPMGuD4bs3U0',
    appId: '1:777154173201:android:fc3b6f2f65b9468f0e94b0',
    messagingSenderId: '777154173201',
    projectId: 'openaamps',
    storageBucket: 'openaamps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEky_XxWxdJ26FHZAUzScaPMGuD4bs3U0',
    appId: '1:777154173201:ios:fc3b6f2f65b9468f0e94b0',
    messagingSenderId: '777154173201',
    projectId: 'openaamps',
    storageBucket: 'openaamps.firebasestorage.app',
    iosBundleId: 'com.openaamps.openAamps',
  );
}
